FROM mcr.microsoft.com/playwright:v1.61.0-jammy

COPY package.json package-lock.json ./
RUN npm ci

COPY playwright.config.ts ./
COPY global-setup.ts ./
COPY ./src/e2e-tests ./src/e2e-tests

CMD [ "npm", "run", "e2e-tests" ]
