FROM mcr.microsoft.com/playwright:v1.61.1-jammy@sha256:2f084b619b7b1fd550b28554424e6df131278b9b96e0976a7304a6269364bba4

WORKDIR /app

RUN npm install @playwright/test@v1.36.1
RUN npx playwright install --with-deps chromium

COPY playwright.config.ts ./
COPY global-setup.ts ./
COPY ./src/e2e-tests ./src/e2e-tests
