FROM mcr.microsoft.com/playwright:v1.58.2-jammy

WORKDIR /app

RUN npm install @playwright/test@v1.36.1
RUN npx playwright install --with-deps chromium

COPY playwright.config.ts ./
COPY global-setup.ts ./
COPY ./src/e2e-tests ./src/e2e-tests
