name: On push main

on:
  push:
    branches:
      - main

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js 24 🧮
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - name: Install dependencies ⏬
        run: npm ci

      - name: Start admin client 🔼
        run: |
          npm run start &
          npx wait-on http://localhost:8080/

      - name: Run service smoke checks 📋
        run: ./smoke-check.sh

  sonarqube:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node 24 🧮
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - name: Cache Node.js modules 💾
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        run: npm ci

      - name: Test code ✅
        run: npm run test
        env:
          CI: true

      - name: Get shogun-admin version 🔖
        run: |
          echo "sonar.projectVersion=$(node -pe "require('./package.json').version")" >> ./sonar-project.properties

      - name: SonarQube Scan 🔬
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
