name: On push main

on:
  push:
    branches:
      - main

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node.js 24 🧮
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Install dependencies ⏬
        run: npm ci

      - name: Start admin client 🔼
        run: |
          npm run start &
          npx wait-on http://localhost:8080/

      - name: Run service smoke checks 📋
        run: ./smoke-check.sh

  sonarqube:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node 24 🧮
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Cache Node.js modules 💾
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        run: npm ci

      - name: Test code ✅
        run: npm run test
        env:
          CI: true

      - name: Get shogun-admin version 🔖
        run: |
          echo "sonar.projectVersion=$(node -pe "require('./package.json').version")" >> ./sonar-project.properties

      - name: SonarQube Scan 🔬
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
