name: On push main

on:
  push:
    branches:
      - e2e-tests

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v4

      - name: Setup Node.js 20 🧮
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies ⏬
        run: npm ci

      - name: Start admin client 🔼
        run: npm run start

      - name: Wait for backend to be ready ⌛
        run: |
          npx wait-on http://localhost:8080/

      - name: Run service smoke checks 📋
        run: ./service-smoke-check.sh

      - name: Install Playwright browsers 🎭
        run: npx playwright install --with-deps

      - name: Run Playwright smoke tests 📋
        run: npm run smoke-tests 

      - name: Upload Playwright report 📄
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

  e2e-tests:
    runs-on: ubuntu-latest
    needs: smoke-tests

    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v4

      - name: Build e2e Docker image 🐋
        run: docker build -t e2e-tests -f ./Dockerfile.e2e .

      - name: Run e2e tests in Docker 📋
        run: |
          docker run --network host \
            e2e-tests npx playwright test

      - name: Upload Playwright report 📄
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

  sonarqube:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node.js 🧮
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node.js modules 💾
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        run: npm ci

      - name: Test code ✅
        run: npm run test
        env:
          CI: true

      - name: Get shogun-admin version 🔖
        run: |
          echo "sonar.projectVersion=$(node -pe "require('./package.json').version")" >> ./sonar-project.properties

      - name: SonarQube Scan 🔬
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
