name: Update docker base images

on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: '0 3 * * 0'  # every sunday at 03:00 UTC

jobs:
  latest-tags:
    runs-on: ubuntu-latest
    outputs:
      main_tag: ${{ steps.main_tag.outputs.result }}
      next_tag: ${{ steps.next_tag.outputs.result }}
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # tags only

      - name: Get latest main tag
        id: main_tag
        run: echo "result=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1 | sed 's/^v//')" >> $GITHUB_ENV

      - name: Get latest next tag
        id: next_tag
        run: echo "result=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(-next\.[0-9]+)?$' | sort -V | tail -n1 | sed 's/^v//')" >> $GITHUB_ENV

  update-docker-main:
    needs: latest-tags
    uses: ./.github/workflows/release_docker.yml
    with:
      release_is_published: true
      release_version: ${{ needs.latest-tags.outputs.main_tag }}
    secrets:
      nexus_user: ${{ secrets.NEXUS_USERNAME}}
      nexus_pass: ${{ secrets.NEXUS_USERNAME}}

  update-docker-next:
    needs: latest-tags
    uses: ./.github/workflows/release_docker.yml
    with:
      release_is_published: true
      release_version: ${{ needs.latest-tags.outputs.next_tag }}
    secrets:
      nexus_user: ${{ secrets.NEXUS_USERNAME}}
      nexus_pass: ${{ secrets.NEXUS_USERNAME}}
